CREATE OR REPLACE VIEW `dion-miguel-0001.wc_ds_001.conversations_predict` AS
SELECT
  MAX(Tickets_Ticket_ID) AS Ticket_ID,
  MAX(Model_DS_Type) AS DS_Type,
  MAX(Sentiment_Assigned) AS Sentiment_Assigned,
  Sentiment AS Label,
  STRING_AGG(CAST(Ticket_Comment_Body AS STRING), ' ') AS Aggregated_Comments,
  STRING_AGG(CASE WHEN Ticket_Comment_Commenter_Is_Doit_Employee__Yes___No_ THEN 'Yes' ELSE 'No' END, ' ') AS Commenter_Employee_Status,
  STRING_AGG(CASE WHEN Ticket_Comment_Commenter_Is_Doit_Support_Bot__Yes___No_ THEN 'Yes' ELSE 'No' END, ' ') AS Commenter_Bot_Status,
  STRING_AGG(CASE WHEN Ticket_Comment_Public__Yes___No_ THEN 'Yes' ELSE 'No' END, ' ') AS Comment_Public_Status,
  STRING_AGG(CAST(Ticket_Comment_Commenter_Name AS STRING), ' ') AS Commenter_Names,
  MAX(Tickets_Created_Date) AS Created_Date,
  MAX(Tickets_Rating) AS Rating,
  MAX(Tickets_Rating_Comment) AS Rating_Comment,
  MAX(Tickets_Rating_Is_Bad_Count) AS Rating_Is_Bad_Count,
  MAX(Tickets_Rating_Is_Good_Count) AS Rating_Is_Good_Count,
  MAX(Tickets_Rating_Is_Good_Percentage) AS Rating_Is_Good_Percentage,
  MAX(Tickets_Rating_Is_Not_Offered_Count) AS Rating_Is_Not_Offered_Count,
  MAX(Tickets_Rating_Is_Offered_Count) AS Rating_Is_Offered_Count,
  MAX(Tickets_Rating_Is_Offered_Percentage) AS Rating_Is_Offered_Percentage,
  MAX(Tickets_Subject) AS Subject,
  MAX(Tickets_Product) AS Product,
  MAX(Tickets_Priority) AS Priority,
  MAX(Tickets_Status) AS Status,
  MAX(Agent_Users_Name) AS Agent_Name,
  MAX(Agent_Users_Region) AS Agent_Region,
  MAX(Agent_Users_Pod) AS Agent_Pod,
  MAX(Tickets_Cloud_Platform) AS Cloud_Platform,
  MAX(Tell_Me_More_Ticket_Effort_Customer_Name) AS Customer_Name,
  MAX(Tell_Me_More_Ticket_Effort_Customer_Segment) AS Customer_Segment,
  MAX(Tickets_Requester_Name) AS Requester_Name,
  MAX(Tickets_Requester_Email) AS Requester_Email,
  MAX(Tickets_Requester_Region) AS Requester_Region,
  MAX(CASE WHEN Tickets_Was_Ticket_Autosolved__Yes___No_ THEN 'Yes' ELSE 'No' END) AS Was_Ticket_Autosolved,
  MAX(CASE WHEN Tickets_Is_Escalated__Yes___No_ THEN 'Yes' ELSE 'No' END) AS Is_Escalated,
  MAX(Tickets_Average_Solve_Time_Days) AS Average_Solve_Time,
  MAX(Tickets_Average_First_Response_Time_Hours) AS Average_First_Response_Time_Hours,
  MAX(Tickets_Average_Customer_Mrr) AS Average_Customer_Mrr,
  MAX(Tickets_First_Response_Time_Miss_Count) AS First_Response_Time_Miss_Count,
  MAX(Tickets_Average_First_Response_Time_Minutes) AS Average_First_Response_Time_Minutes,
  SUM(Ticket_Comment_Comment_Count) AS Total_Comments,
  MAX(Issue_Assigned) AS Issue_Assigned,
  MAX(Resolution_Assigned) AS Resolution_Assigned,
  MAX(CASE WHEN Tell_Me_More_Ticket_Effort_Is_Get_Doer_Request__Yes___No_ THEN 'Yes' ELSE 'No' END) AS Is_Get_Doer_Request,
  MAX(CASE WHEN Tickets_Is_Getcre__Yes___No_ THEN 'Yes' ELSE 'No' END) AS Is_Getcre,
  MAX(CASE WHEN Tickets_Requester_Is_From_Doit__Yes___No_ THEN 'Yes' ELSE 'No' END) AS Requester_Is_From_Doit,
  MAX(CASE WHEN Tickets_Is_Public__Yes___No_ THEN 'Yes' ELSE 'No' END) AS Is_Public,
  MAX(CASE WHEN Tell_Me_More_Ticket_Effort_Ticket_Is_Pss__Yes___No_ THEN 'Yes' ELSE 'No' END) AS Ticket_Is_Pss,
  MAX(Tickets_Ticket_Count) AS Ticket_Count,
  MAX(RANDO) AS RANDO,
  MAX(RANDT) AS RANDT
FROM
  `dion-miguel-0001.wc_ds_001.tickets_predict_view`
GROUP BY Tickets_Ticket_ID, Sentiment;
