CREATE OR REPLACE TABLE `looker-tickets.zendesk.new_tickets` AS
SELECT
  `Tickets Ticket ID` AS Ticket_ID,
  `Tickets Created Date` AS Created_Date,
  `Tickets Priority` AS Priority,
  `Tickets Status` AS Status,
  `Tickets Is Escalated _Yes _ No_` AS Is_Escalated,
  `Tickets Was Ticket Autosolved _Yes _ No_` AS Is_Autosolved,
  `Tickets Requester Is From Doit _Yes _ No_` AS Is_Requester_From_Doit,
  `Tickets Is Getcre _Yes _ No_` AS Is_Getcre,
  `Tickets Is Public _Yes _ No_` AS Is_Public,
  `Tickets First Response Time Slo Breach _Yes _ No_` AS Is_FRT_Slo_Breach,
  `Tickets Cloud Support Case Used _Yes _ No_` AS Is_Cloud_Support_Case_Used,
  `Tickets Cloud Platform` AS Cloud_Platform,
  `Tickets Practice Area` AS Practice_Area,
  `Tickets Skill Group` AS Skill_Group,
  `Tickets Product` AS Product,
  `Tickets Subject` AS Subject,
  `Tickets Agent User ID` AS Agent_User_ID,
  `Tickets Agent Name` AS Agent_Name,
  `Tickets Agent Pod` AS Agent_Pod,
  `Tickets Agent Region` AS Agent_Region,
  `Tickets Agent Time Zone` AS Agent_Time_Zone,
  `Tickets Requester ID` AS Requester_ID,
  `Tickets Requester Name` AS Requester_Name,
  `Tickets Requester Email` AS Requester_Email,
  `Tickets Requester Organization Name` AS Requester_Organization_Name,
  `Tickets Requester Region` AS Requester_Region,
  `Tickets Requester Time Zone` AS Requester_Time_Zone,
  `Tickets Rating` AS Rating,
  `Tickets Rating Comment` AS Rating_Comment,
  `Tickets Rating Comment Length` AS Rating_Comment_Length,
  `Tickets Rating Is Offered` AS Rating_Offered,
  `Issue`,
  `Resolution`,
  `AgentScore` AS Agent_Score,
  `RND_T`,
  `Sentiment`,
  `Sentiment Heuristic` AS Sentiment_Heuristic,
  `Sentiment Integer` AS Sentiment_Integer,
  `Tickets Average Solve Time Hours` AS Average_Solve_Time_Hours,
  `Tickets Average First Response Time Hours` AS Average_FRT_Hours,
  `Tickets Average Customer Mrr` AS Average_Customer_Mrr,
  `Tickets Count` AS Count
FROM
  `looker-tickets.zendesk.tickets`;